pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        // Correct the git step by using proper syntax
          git credentialsId: 'github-creds',
          url: 'https://github.com/etechteam6/jenkins-folder.git',
          branch: 'master'
      }
    }

    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }

    stage('Integration test') {
      agent {
        docker { image 'adoptopenjdk:11-jdk-hotspot' }
      }
      steps {
        sh 'echo "Running integration tests"'
        sh 'java -version'
        sh 'node --version'
      }
    }
  }
}
