pipeline {
  agent none
  stages {
     stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', // ID of your credentials
                url: 'https://github.com/etechteam6/jenkins-folder.git' // URL of your Git repository
                branch: "master"
            }
        }

    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Integration test') {
      agent {
        docker { image 'adoptopenjdk:11-jdk-hotspot' }
      }
       steps {
        sh 'echo "Running integration tests"'
        // Example test command, replace with actual test command for your environment
        sh 'java -version'
        sh 'node --version' // Assuming Node.js is also installed on this image for simplicity
      }
    }
  }
}
